apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriber-deployment
  labels:
    app: subscriber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscriber
  template:
    metadata:
      labels:
        app: subscriber
    spec:
      containers:
      - name: subscriber
        image: dashenflashen/kubernetes-queue:subscriber
        env:
        - name: RABBIT_HOST
          value: "rabbitmq-service"
        - name: RABBIT_PORT
          value: "5672"
        - name: RABBIT_QUEUE
          value: "subscriber_queue"
        - name: APP_HOST
          value: "api-service"
        - name: APP_PORT
          value: "9000"
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: subscriber-service
spec:
  selector:
    app: subscriber
  ports:
    - name: http
      port: 8080
      targetPort: 8080
